repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-featureextractor_logo_light.png
    - docs/images/nf-core-featureextractor_logo_light.png
    - docs/images/nf-core-featureextractor_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - CHANGELOG.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - CHANGELOG.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-featureextractor_logo_light.png
    - docs/images/nf-core-featureextractor_logo_light.png
    - docs/images/nf-core-featureextractor_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: itrujnara
  name: featureextractor
  description: A small pipeline to extract feature sequences from a FASTA based on
    a GFF annotation.
  author: Igor Trujnara
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - changelog
    - email
    - adaptivecard
    - slackreport
    - documentation
    - test_config
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
